import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { useAddress, useNetworkMismatch, useNetwork, ConnectWallet, ChainId } from "@thirdweb-dev/react"
import { useExplorePublicationsQuery, PublicationSortCriteria } from "../graphql/generated"
import useLogin from "../lib/auth/useLogin";
export default function Home() {
  const { mutate: requestLogin } = useLogin();
  const address = useAddress()

  if(!address) {
    return <ConnectWallet />
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => requestLogin()}>Login</button>
    </>
  )
}
