import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
const inter = Inter({ subsets: ['latin'] })
import {useExplorePublicationsQuery, PublicationSortCriteria} from "../graphql/generated"

export default function Home() { 
  // const {data, isLoading, error} = useExplorePublicationsQuery(
  //   {
  //   endpoint: "https://api.lens.dev",
  //   fetchParmas: {
  //     headers: {
  //       "Content-Type": "application/json",
  //     }
  //   },
  // }, {
  //   request: {
  //     sortCriteria: PublicationSortCriteria.TopCollected,
  //   },
  // })

  const { isLoading, error, data } = useExplorePublicationsQuery(
    {
      request: {
        sortCriteria: PublicationSortCriteria.Latest,
      },
    },
    {
      // Don't refetch the user comes back
      refetchOnWindowFocus: false,
      refetchOnReconnect: false,
    }
  );

  console.log({data, isLoading, error})
  return (
    <>
      <Head> 
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" /> 
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       
      <div>Hello World</div>
    </>
  )
}
